FROM node:18-alpine

WORKDIR /app

# Устанавливаем зависимости
COPY package*.json ./
RUN npm install

# Копируем исходный код
COPY . .

# Для разработки используем nodemon
RUN npm install -g nodemon

CMD ["nodemon", "--inspect=0.0.0.0:9229", "src/app.ts"]